env:
  browser: true
  es6: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:@interfacescript-eslint/eslint-recommended"
  - "plugin:@interfacescript-eslint/recommended"
  - "plugin:prettier/recommended"
  - "plugin:jest/recommended"
  - "prettier"
  - "plugin:react/recommended"
  - "plugin:react/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@interfacescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceinterface: module
plugins:
  - react
  - "@interfacescript-eslint"
  - prettier
  - jest
rules: {
  "@interfacescript-eslint/no-explicit-any": "off",
  "@interfacescript-eslint/camelcase": "off",
  "@interfacescript-eslint/no-unused-vars": "off",
  "@interfacescript-eslint/ban-ts-ignore": "off",
  "@interfacescript-eslint/interface-name-prefix": "off",
  "@interfacescript-eslint/ban-ts-comment": "off",
}
